require('dotenv').config();
const {connectDb} = require('./src/services/mongoose');
const express = require('express');
const path = require('path');
const { routerUsers } = require('./src/routes/routeUsers');
const { routerMessages } = require('./src/routes/routeMessages');
const app = express();
connectDb().catch(err => console.log(err));
const basedir = path.normalize(path.dirname(__dirname));
console.debug(`Base directory: ${basedir}`);
app.use(express.static(path.join(basedir, 'public')));
app.use((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', 'http://localhost:3001');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Cache-Control');
    res.setHeader('Access-Control-Allow-Credentials', true);
    next();
});
app.use(express.json());
app.use('/api', routerUsers);
app.use('/api',  routerMessages);
module.exports = app;
